version: "3"
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    networks:
      - network
    depends_on:
      - wordpress
    restart: always
    ports:
      # - "443:443"
      - "80:80"
    volumes:
      - ~/data/wp_html:/var/www/html # change to /home/gvial/data/wp_html

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - network
    depends_on:
      - mariadb
    restart: always
    expose:
      - "9000"
    volumes:
      - ~/data/wp_html:/var/www/html # change to /home/gvial/data/wp_html
    environment:
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_HOST: mariadb:3306

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - network
    restart: always
    expose:
     - "3306"
    volumes:
      - ~/data/wp_db:/wp_db # change to /home/gvial/data/wp_db
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_password
      MYSQL_DATABASE: wp_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
networks:
  network:
