version: "3"

services:

  mariadb:
    build: ./requirements/mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - network

  wordpress:
    build: ./requirements/wordpress
    restart: always
    environment:
      - DOMAIN_NAME=gvial.42.fr
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_EMAIL=${MYSQL_EMAIL}
      - MYSQL_SERVER=${MYSQL_SERVER}
      - WP_USER=${WP_USER}
      - WP_PWD=${WP_PWD}
      - WP_EMAIL=${WP_EMAIL}
    volumes:
      - wordpress:/var/www/html/
    networks:
      - network
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - network

volumes:
  mariadb:
    driver: local
    external: true
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/mariadb

  wordpress:
    driver: local
    external: true
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/wordpress

networks:
  network: