version: "3"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - network
    restart: always
    volumes:
      - ${VOLUME_PATH}/mariadb:${MYSQL_DATADIR}
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATADIR: ${MYSQL_DATADIR}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - network
    expose:
      - "9000"
    depends_on:
      - mariadb
    restart: always
    volumes:
      - ${VOLUME_PATH}/wordpress:/var/www/html
    environment:
      WP_USER: ${WP_USER}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_HOST: mariadb:3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_SERVER: ${MYSQL_SERVER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    networks:
      - network
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always
    volumes:
      - ${VOLUME_PATH}/wordpress:/var/www/html

networks:
  network:
